target-version = "py311"

lint.select = ["ALL"]

lint.ignore = [
    "BLE001",   # Do not catch blind exception: `Exception`
    "C901",     # is too complex
    "COM812",   # Trailing comma missing (conflicts with formatter)
    "D203",     # 1 blank line required before class docstring (conflicts with `no-blank-line-before-class` (D211))
    "D213",     # Multi-line docstring summary should start at the second line (conflicts with multi-line-summary-first-line` (D212))
    "PLR0912",  # Too many branches
    "PLR0915",  # Too many statements
    "TRY301",   # Abstract `raise` to an inner function
]


[lint.per-file-ignores]
"examples/*" = [
    "T201",      # `print` found
]
