"""webOS registration payload."""

REGISTRATION_PAYLOAD = {
    "forcePairing": False,
    "manifest": {
        "appVersion": "1.1",
        "manifestVersion": 1,
        "permissions": [
            "APP_TO_APP",
            "CLOSE",
            "CONTROL_AUDIO",
            "CONTROL_DISPLAY",
            "CONTROL_INPUT_JOYSTICK",
            "CONTROL_INPUT_MEDIA_PLAYBACK",
            "CONTROL_INPUT_MEDIA_RECORDING",
            "CONTROL_INPUT_TEXT",
            "CONTROL_INPUT_TV",
            "CONTROL_MOUSE_AND_KEYBOARD",
            "CONTROL_POWER",
            "CONTROL_TV_SCREEN",
            "LAUNCH",
            "LAUNCH_WEBAPP",
            "READ_APP_STATUS",
            "READ_COUNTRY_INFO",
            "READ_CURRENT_CHANNEL",
            "READ_INPUT_DEVICE_LIST",
            "READ_INSTALLED_APPS",
            "READ_LGE_SDX",
            "READ_LGE_TV_INPUT_EVENTS",
            "READ_NETWORK_STATE",
            "READ_NOTIFICATIONS",
            "READ_POWER_STATE",
            "READ_RUNNING_APPS",
            "READ_SETTINGS",
            "READ_TV_CHANNEL_LIST",
            "READ_TV_CURRENT_TIME",
            "READ_UPDATE_INFO",
            "SEARCH",
            "TEST_OPEN",
            "TEST_PROTECTED",
            "TEST_SECURE",
            "UPDATE_FROM_REMOTE_APP",
            "WRITE_NOTIFICATION_ALERT",
            "WRITE_NOTIFICATION_TOAST",
            "WRITE_SETTINGS",
        ],
    },
    "pairingType": "PROMPT",
}


REGISTRATION_MESSAGE = {
    "type": "register",
    "id": "register_0",
    "payload": REGISTRATION_PAYLOAD,
}
